name = "btcmirror-submitter"

main = "src/index.ts"
compatibility_date = "2022-09-19"
node_compat = true

[vars]
BTCMIRROR_CONTRACT_ADDR="TODO"
ETH_RPC_URL="https://goerli.infura.io/v3/c2098b0ca85643b1ad367c0f479c98f0"
BITCOIN_NETWORK="testnet"

# Secrets: 
# - ETH_SUBMITTER_PRIVATE_KEY
# - GETBLOCK_API_KEY
# Run `echo <val> | wrangler secret put <key>`

[triggers]
crons = [ "* * * * *" ]
